language: java
jdk:
- openjdk7
notifications:
  email: change
after_success:
- rsync -avz target -e 'ssh -i .travis/happiserver' mvserver@happi.pw:/home/mcserver/build
addons:
  ssh_known_hosts:
  - happi.pw
