name: CollectiveLearning
main: com.yoerik.MCCollectiveLearning.MCCollectiveLearning
version: 0.11

commands:
   cl:
      description: The main command for the collective learning game manager plugin
      usage: /cl help
      permission-message: You don't have CollectiveLearning.main

      
